### ISSUE TITLE
I can't install packages from requirements.txt with command [pip install -r requirements.txt]

### ISSUE THREAD

**Issue by telunyang** [DigitalPhonetics/adviser#1]
### OS
Windows 10

### Tool
1. Anaconda Prompt
2. conda 4.7.1
3. python 3.7.4
4. pip 19.2.2

### Description
I've installed _virtualenv_ and _venv_ folder as you indicated from README file, then I've launched _venv_ script "activate" to build a virtual environment for adviser.

Afterward, I typed a command [pip install -r requirements.txt] and got the following error message soon: 

(**venv**) (**myEnv**) _C:\Users\users\source\repos\adviser>**pip install -r requirements.txt**
Collecting torch>=1.0.0 (from -r requirements.txt (line 1))
  ERROR: Could not find a version that satisfies the requirement torch>=1.0.0 (from -r requirements.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.0.0 (from -r requirements.txt (line 1))

How should I solve this error event? Thanks in advance.

**Comment by mxschmdt** [comment]
Hi telunyang,
unfortunately the recent versions of torch are not available on the Python Package Index (PyPI) for Windows. Please install torch directly from [here](https://pytorch.org/get-started/locally/) or use the updated requirements.txt.

Thanks for your feedback :)
Max

**Comment by telunyang** [comment]
> Hi telunyang,
> unfortunately the recent versions of torch are not available on the Python Package Index (PyPI) for Windows. Please install torch directly from [here](https://pytorch.org/get-started/locally/) or use the updated requirements.txt.
> 
> Thanks for your feedback :)
> Max

Understood. 
Thanks anyway.

BTW, it was successful to build **advisor** via Anaconda 4.7.1 environment on Ubuntu 18.04 server. It means your instructions of README file are clear and applicable to use in any UNIX-like system.

**Comment by mxschmdt** [comment]
That's good to know! :)
We use different Linux distributions for development, but usually not a Windows machine. However it should work there as well.
