### ISSUE TITLE
Check tests for simulator module

### ISSUE THREAD

**Issue by SarinaMeyer** [DigitalPhonetics/adviser#11]
Please check the tests for the whole simulator module. You can find them in tests/simulator/ and they include tests for Simulator, Agenda, Goal and EmotionSimulator.

**Comment by lvanderlyn** [comment]
@SarinaMeyer these look really good! Based on Max's comments on the other issues, I think you should probably delete the three tests that are failing since those conditions should not be possible to reach. Once you do that, we can close this issue :)
