### ISSUE TITLE
graphviz failed to execute

### ISSUE THREAD

**Issue by e-tony** [DigitalPhonetics/adviser#5]
Hi,

for Ubuntu 18.04, I received the following error from graphviz when running the tutorial:

```
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpng', '-O', 'tutorial.gv'], make sure the Graphviz executables are on your systems' PATH
```

Installing the package on Ubuntu fixed the problem.

```
sudo apt-get install graphviz
```

**Comment by sheogorath15** [comment]
Github page is updated accordingly, added a note to the installation tutorial as well

**Comment by mxschmdt** [comment]
Thanks @e-tony for mentioning!
I'll close this as you found the fix and it has been added to the instructions.
