### ISSUE TITLE
Bug: Simulator: wrong expected value of system action

### ISSUE THREAD

**Issue by SarinaMeyer** [DigitalPhonetics/adviser#8]
In the methods _receive_confirmrequest (line 397) and _check_system_ignored_request (line 657) in the simulator.py,it is assumed that the value in sys_act.slot_values is a single value, but it should be a list of several values

**Comment by mxschmdt** [comment]
As an additional note, I did not change the first part because a confirm (and confirmrequest) system action can only contain a single value.
